---
server:
  port: 8080
spring:
  profiles:
    active: Mysql
logging:
  level:
    com.example.demo: trace
  file:
    name:
---
server:
  port: 9665
spring:
  config:
    activate:
      on-profile: Mysql
  datasource:
    #数据源基本配置
    username: tester
    password: tester
    url: jdbc:mysql://localhost:3306/testplatform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery:  SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters,去掉后监控界面sql无法统计，‘wall’用于防火墙
    filters: [stat,wall,log4j]
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #设置数据库初始化
    #schema:
    #  - classpath:sql/function_mysql.sql
    #  - classpath:sql/logEvent.sql
    initialization-mode: always
  jpa:
    hibernate:
      #创建或更新数据表结构
      ddl-auto: update
#    显示sql
    show-sql: true
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 20000
mybatis:
  config-location: classpath:mybatis/mybatis_config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
---
server:
  port: 9666
spring:
  config:
    activate:
      on-profile: Oracle
  datasource:
    #数据源基本配置
    username: ktauto
    password: ktauto
    url: jdbc:oracle:thin:@oel1247.hz.asiainfo.com:1521:oel1247
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    schema:
#      - classpath:sql/function_oracle.sql
#    initialization-mode: always
